local text = SB.new()
SB.append(text, Female.Name.."的穿着".."\n")
SB.append(text, "头"..Female : GetOutsideEquip(0).."\n")
SB.append(text, "眼"..Female : GetOutsideEquip(1).."\n")
SB.append(text, "嘴"..Female : GetOutsideEquip(2).."\n")
SB.append(text, "脖子"..Female : GetOutsideEquip(3).."\n")
SB.append(text, "手"..sFemale : GetOutsideEquip(4).."\n")
SB.append(text, "身体"..Female : GetOutsideEquip(5).."\n")
SB.append(text, "腿"..Female : GetOutsideEquip(6).."\n")
SB.append(text, "脚"..Female : GetOutsideEquip(7).."\n")
Message : AddMessage(SB.tostr(text))